<?php echo form::open() ; ?>
   <div class =''>
         <div class='col s6'>
              <label for='Nombres'>Nombres
            <?php echo form::text('alumnos.nombres', 'placefolder='Ej. Moises Bonilla''); ?></label>
       </div>
       <div class='col s6'>
     </div>

             <?php echo form::close() ; ?> 
    <label for='apellidos'>Apellidos
    <?php echo form::text'alumnos.apellidos','placefolder='Ej. Moises Bonilla''); ?> </label>
    </div>
    
    <div class='col s6'>
    <label for='Telfono'>Telefono
    <?php echo form::text('alumnos.telefono', 'placefolder='ej. 8398238483483''); ?>
    </label>
    <div  class='col s6'>
    <?php echo form::sumit('Guardar'; 'class='btn green); ?>
          </div>
         </div>
    <?php echo form::clase()); ?>