<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title><?php echo titulo ?></title>
</head>
<body>
<nav class="blue darken-3"></nav>
<ul>
    <li><?php echo Html::limk('alumno', 'linea de Alunos');
    ?>
    </li>
    <li><?php echo Html::('alumnos/contactos', 'listen de contactos')
    ?>
</ul>

 <div class="container">
 <?php 
     View::content(); 
 ?>
 </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>    
</body>

            
</html>